gg.jte.development-mode=true
spring.application.name=shoe-store

spring.datasource.url=jdbc:postgresql://localhost:5432/shoe-store
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none