@param String title
@param gg.jte.Content content

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" href="/styles/styles.css">
</head>
<body>
<header>
    <div class="header-content">
        <a href="/" class="logo-link">
            <h1>👟 Best-shoes</h1></a>
        <nav>
            <a href="/">Home</a>
            <a href="/about">About</a>
            <a href="/register">Sign up</a>
        </nav>
    </div>
</header>
<main>
    ${content}
</main>
<footer>
    <p>&copy; 2025 Best Shoes. All rights reserved.</p>
</footer>
</body>
</html>